### ISSUE TITLE
How do I install this?

### ISSUE THREAD

**Issue by RoyalWulf** [LetPeopleWork/AzureDevOpsFlowScripts#2]
I don't know anything about python
I downloaded MonteCarlo.py, I modified it for my Area Paths
then tried to run it by
python .\MonteCarlo.py  --OrganizationUrl "https://dev.azure.com/MyOrg/" --PersonalAccessToken "XXXX" --ReleaseTag "MyProduct v1.33.7" --TargetDate "08.04.2024" --GoalTag "SprintGoal" --IterationLength "7"

I get
Traceback (most recent call last):
  File "C:\Users\jge22\AppData\Local\Programs\Python\Python312\MonteCarlo.py", line 4, in <module>
    from Services.WorkItemService import WorkItemService
ModuleNotFoundError: No module named 'Services'

How do I fix this?

cheers

**Comment by huserben** [comment]
Hi @RoyalWulf 

did you download just the MonteCarlo script? Because you need all folders for it to work.

The error message looks like it does not find some of the files in the subfolders.

Let me know whether this solved your problem.

**Comment by RoyalWulf** [comment]
Hi @huserben,
Got there in the end thank you.
Suggest you put some instructions in your readme?

Cheers

**Comment by huserben** [comment]
Thanks @RoyalWulf 

and you are correct about the instructions. I've updated the ReadMe now (see also #3 ) so that it contains a section about the fact that you need the full folder.

Thanks for raising this!
