### ISSUE TITLE
Area Path length

### ISSUE THREAD

**Issue by RoyalWulf** [LetPeopleWork/AzureDevOpsFlowScripts#4]
Is there a limit to Area Path length?

I get this issue:
![image](https://github.com/huserben/AzureDevOpsPythonScripts/assets/103555625/6e31a4e2-d432-456d-846b-4edd7790beb5)

If I shorten the path I don't get the issue
There is no unicode issues that i can see and works if i shorten the path

**Comment by huserben** [comment]
Hi @RoyalWulf 

can you try to "escape" the backslashes?

To do that, you simply add a second \.
So "..\\Digital Channel .. \\ ..."

**Comment by huserben** [comment]
Hi again @RoyalWulf 

Sorry, somehow I missed the part where you said it works with a shorter path. From what I can see, there should not be any problem with longer paths. Can it be some strange copy/paste issue perhaps, like some strange symbol at the end of the string? If you remove the whole area path and type it in by hand, does it work then?

**Comment by huserben** [comment]
@RoyalWulf did you manage to solve this problem?

**Comment by huserben** [comment]
Closed due to inactivity
