### ISSUE TITLE
Using ActivatedDate instead of ChangeDate

### ISSUE THREAD

**Issue by 2moveit** [LetPeopleWork/AzureDevOpsFlowScripts#7]
Hi, thanks for the great script. 
I've run into a problem because I don't want to track the change from the NEW state, but when it goes to the first In Progress state, because I have defined further “Proposed” states in addition to the NEW.
To do this, I use the ActivatedDate instead of the now commented-out calculation using the ChangedDate.

```
def extract_age(work_item_history):
    for history_entry in work_item_history["value"]:
        if "fields" in history_entry and "Microsoft.VSTS.Common.ActivatedDate" in history_entry["fields"]:
            activated_date = parse_ado_date(history_entry["fields"]["Microsoft.VSTS.Common.ActivatedDate"]["newValue"])
    
     #   if "fields" in history_entry and "System.State" in history_entry["fields"]:
     #       state_change = history_entry["fields"]["System.State"]
     #       changed_date_field = history_entry["fields"]["System.ChangedDate"]

     #       if "oldValue" in state_change and "newValue" in changed_date_field:
     #           old_state = state_change["oldValue"]
     #           new_state = state_change["newValue"]
     #           changed_date = parse_ado_date(changed_date_field["newValue"])

                # When it was moved "out of new" we care -> count days from then till today + 1 -> that's our WIA
      #          if old_state == "New":
                    
      #              work_item_age = (date_today - changed_date.date()).days + 1
      #              print("Item was moved from {0} to {1} on {2} -> Work Item Age: {3}".format(old_state, new_state, changed_date, work_item_age))

            work_item_age = (date_today - activated_date.date()).days + 1
            print("Item was activated on {0} -> Work Item Age: {1}".format(activated_date, work_item_age))
            return work_item_age
    return 0
```

I just wanted to leave my adjustment here so that someone else could benefit from it if necessary. 
If your next state is also defined under "In Progress", then the same should come out. 

Or do you see problems with this approach that have led you to use the ChangeDate?

Cheers

**Comment by huserben** [comment]
Hi @2moveit 

I don't see any problem, and I think it's the smarter solution. I think when I first created this script, I was just not aware how to do it better.
I'll have a more detailed looked (hopefully over the weekend) and will update the code accordingly. Relying on the "State Categories" rather than the states is more generic, I'm sure you're not the only one having more than one state in the "Proposed" category 👍

**Comment by huserben** [comment]
"Your" version is now the one that is used in general, as I updated the script in 430955a

Thanks a lot for your input!
